require("dotenv").config();
const express=require("express"),{Pool}=require("pg"),crypto=require("crypto"),jwt=require("jsonwebtoken");
const app=express(),port=Number(process.env.PORT||3000);
const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.DATABASE_URL&&!/localhost|127\.0\.0\.1/.test(process.env.DATABASE_URL)?{rejectUnauthorized:false}:false});
const SERVICES={"Corte":25,"Sobrancelha":10,"Barba":25,"Bigode":5,"Pigmentação":60,"Nevou":140,"Reflexo":130,"Colorimetria + Corte":120,"Combo Especial":35};
app.use(express.json());app.use(express.static("public"));
const clean=(v,n=200)=>String(v??"").trim().slice(0,n);
const validDate=v=>/^\d{4}-\d{2}-\d{2}$/.test(v),validTime=v=>/^([01]\d|2[0-3]):[0-5]\d$/.test(v);
async function mp(path,opt={}){const r=await fetch("https://api.mercadopago.com"+path,{...opt,headers:{"Authorization":"Bearer "+process.env.MP_ACCESS_TOKEN,"Content-Type":"application/json",...(opt.headers||{})}});const t=await r.text();let d={};try{d=t?JSON.parse(t):{}}catch{}if(!r.ok){const e=new Error(d.message||"Mercado Pago error");e.data=d;throw e}return d}
function signature(req){const s=req.get("x-signature")||"",rid=req.get("x-request-id")||"",p=Object.fromEntries(s.split(",").map(x=>x.split("=",2)).filter(x=>x.length===2)),id=req.query["data.id"]||req.body?.data?.id;if(!p.ts||!p.v1||!rid||!id||!process.env.MP_WEBHOOK_SECRET)return false;const base=`id:${String(id).toLowerCase()};request-id:${rid};ts:${p.ts};`,h=crypto.createHmac("sha256",process.env.MP_WEBHOOK_SECRET).update(base).digest("hex");try{return crypto.timingSafeEqual(Buffer.from(h),Buffer.from(p.v1))}catch{return false}}
function auth(req,res,next){try{req.user=jwt.verify((req.headers.authorization||"").replace(/^Bearer\s+/i,""),process.env.JWT_SECRET);next()}catch{res.status(401).json({error:"Não autorizado"})}}

app.get("/api/services",(q,r)=>r.json(SERVICES));
app.get("/api/slots",async(req,res)=>{const d=clean(req.query.date,10);if(!validDate(d))return res.status(400).json({error:"Data inválida"});await pool.query("UPDATE bookings SET status='expired',updated_at=NOW() WHERE status='pending' AND expires_at<NOW()");const x=await pool.query("SELECT to_char(appointment_time,'HH24:MI') time FROM bookings WHERE appointment_date=$1 AND status IN ('pending','approved')",[d]);res.json({blocked:x.rows.map(a=>a.time)})});

app.post("/api/bookings",async(req,res)=>{
const name=clean(req.body.name,100),whatsapp=clean(req.body.whatsapp,30),email=clean(req.body.email,160),service=clean(req.body.service,80),date=clean(req.body.date,10),time=clean(req.body.time,5);
if(!name||!whatsapp||!email||!SERVICES[service]||!validDate(date)||!validTime(time))return res.status(400).json({error:"Preencha todos os campos corretamente."});
const id=crypto.randomUUID(),expires=new Date(Date.now()+30*60*1000),client=await pool.connect();
try{await client.query("BEGIN");await client.query("UPDATE bookings SET status='expired' WHERE status='pending' AND expires_at<NOW()");
await client.query("INSERT INTO bookings(id,customer_name,whatsapp,email,service,price,appointment_date,appointment_time,expires_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)",[id,name,whatsapp,email,service,SERVICES[service],date,time,expires]);await client.query("COMMIT")}catch(e){await client.query("ROLLBACK");if(e.code==="23505")return res.status(409).json({error:"Esse horário acabou de ser reservado."});return res.status(500).json({error:"Não foi possível reservar o horário."})}finally{client.release()}
try{const p=await mp("/v1/payments",{method:"POST",headers:{"X-Idempotency-Key":id},body:JSON.stringify({transaction_amount:Number(SERVICES[service]),description:`${service} — TH_DU_CORTE033`,payment_method_id:"pix",external_reference:id,date_of_expiration:expires.toISOString(),payer:{email,first_name:name.split(" ")[0]}})}),tx=p.point_of_interaction?.transaction_data||{};await pool.query("UPDATE bookings SET payment_id=$1,payment_status=$2,pix_copy_paste=$3,pix_qr_base64=$4,updated_at=NOW() WHERE id=$5",[String(p.id),p.status||"pending",tx.qr_code||null,tx.qr_code_base64||null,id]);res.json({bookingId:id,qrCode:tx.qr_code||null,qrCodeBase64:tx.qr_code_base64||null})}catch(e){await pool.query("UPDATE bookings SET status='canceled' WHERE id=$1",[id]);console.error(e.data||e);res.status(502).json({error:"Não foi possível criar o Pix."})}
});
app.get("/api/bookings/:id/status",async(req,res)=>{const x=await pool.query("SELECT id,status,payment_status,customer_name,service,appointment_date,to_char(appointment_time,'HH24:MI') appointment_time FROM bookings WHERE id=$1",[req.params.id]);if(!x.rowCount)return res.status(404).json({error:"Agendamento não encontrado"});res.json(x.rows[0])});
app.post("/api/webhooks/mercadopago",async(req,res)=>{if(!signature(req))return res.status(401).send("invalid signature");res.sendStatus(200);const pid=req.body?.data?.id||req.query["data.id"];if(!pid)return;try{const p=await mp("/v1/payments/"+encodeURIComponent(pid)),id=p.external_reference;if(!id)return;if(p.status==="approved")await pool.query("UPDATE bookings SET status='approved',payment_status='approved',updated_at=NOW() WHERE id=$1 AND status='pending'",[id]);else if(["rejected","cancelled","refunded","charged_back"].includes(p.status))await pool.query("UPDATE bookings SET status='canceled',payment_status=$2,updated_at=NOW() WHERE id=$1 AND status='pending'",[id,p.status]);else await pool.query("UPDATE bookings SET payment_status=$2 WHERE id=$1",[id,p.status])}catch(e){console.error("webhook",e)}});
app.post("/api/admin/login",async(req,res)=>{if(!process.env.ADMIN_PASSWORD||req.body.password!==process.env.ADMIN_PASSWORD)return res.status(401).json({error:"Senha incorreta"});res.json({token:jwt.sign({role:"barber"},process.env.JWT_SECRET,{expiresIn:"12h"})})});
app.get("/api/admin/bookings",auth,async(req,res)=>{const x=await pool.query("SELECT id,customer_name,whatsapp,email,service,price,appointment_date,to_char(appointment_time,'HH24:MI') appointment_time,status,payment_status,created_at FROM bookings ORDER BY appointment_date,appointment_time");res.json(x.rows)});
app.get("/api/admin/summary",auth,async(req,res)=>{const x=await pool.query("SELECT COUNT(*) FILTER(WHERE status IN('pending','approved'))::int total,COUNT(*) FILTER(WHERE status='approved')::int paid,COALESCE(SUM(price) FILTER(WHERE status='approved'),0) revenue FROM bookings");res.json(x.rows[0])});
app.listen(port,()=>console.log("TH_DU_CORTE033 na porta "+port));
